version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fp1-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: fp1
      POSTGRES_DB: idpbook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fp1-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fp1-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: fabricio.santana@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - fp1-network

volumes:
  postgres_data:

networks:
  fp1-network:
    driver: bridge